// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nffkduyqvyuvrjaluyba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mZmtkdXlxdnl1dnJqYWx1eWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNzQ4OTYsImV4cCI6MjA1Njg1MDg5Nn0.l_irUO8CPBbAL3XFljTklO-qE60T9EUthUipw_gDp9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);